### ISSUE TITLE
missing file 'resource/skinning_weight_r.npy'

### ISSUE THREAD

**Issue by WeedsInML** [korrawe/halo#3]
Hello,

Thank you for your great work.
I am trying to train halo_base by myself. When I run "prepare_data_from_mano_param_keypoints.py", I cannot find the file 'resource/skinning_weight_r.npy'. Could you share it?

**Comment by korrawe** [comment]
Hi, 
I added it there now, sorry for the delay. These are the weights derived from MANO so you could also find them inside the ManoLayer if you want to cross-check.
Best.
